# Generated by Django 4.2.5 on 2024-08-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='server',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
