# Generated by Django 4.2.5 on 2024-08-07 16:22

from django.db import migrations, models
import server.models
import server.validators


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_category_slug_alter_channel_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server_icon_upload_path, validators=[server.validators.validate_image_file_extension]),
        ),
    ]
