# Generated by Django 4.2.5 on 2024-08-07 16:23

from django.db import migrations, models
import server.models
import server.validators


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_server_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.channel_icon_upload_path, validators=[server.validators.validate_image_file_extension]),
        ),
    ]
